spring:
  application:
    name: ai-linguo-backend
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ailinguo}
    username: ${DB_USERNAME:ailinguo}
    password: ${DB_PASSWORD:ailinguo123}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: ${JWT_SECRET:58a19f8830f8b701c64d6130285277fcfe80ae7509e9afbdb212a2557448df90ec94a4b8e414be657462ae1d52fad28cb43cdc110e5f4275ef2c5a441949a0a7}
    expiration: 604800000 # 7 days in milliseconds
  
  openai:
    api-key: ${OPENAI_API_KEY:}
    model: ${OPENAI_MODEL:gpt-4o-mini}
    model-fallback: ${OPENAI_MODEL_FALLBACK:gpt-4o}
    mock-mode: ${AI_TUTOR_MOCK:true}
  
  cors:
    "[allowed-origins]": ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

logging:
  level:
    com.ailinguo: DEBUG
    org.springframework.security: DEBUG

